spring.application.name=ejercicio1

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.hrzlavdwmvfkcdfmaqdg&password=MjgmrQznfNSmIeIs
spring.datasource.username=postgres.hrzlavdwmvfkcdfmaqdg
spring.datasource.password=MjgmrQznfNSmIeIs

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

server.port=${PORT:8080}